export const LOAD_USERS = 'LOAD_USERS'

export const SELECT_TAB = 'SELECT_TAB'

export const UPDATE_IMPORT_USERS_TEXT = 'UPDATE_IMPORT_USERS_TEXT'

export const EXECUTE_IMPORT_USERS = 'EXECUTE_IMPORT_USERS'
export const NOTIFY_IMPORT_USER = 'NOTIFY_IMPORT_USER'
